#!/bin/bash
clear

echo ---------- REMOVING 	PREVIOUS 	BUILD ----------
rm ./src/BlockWorld

echo ---------- MAKING 	NEW 		BUILD ----------
make

echo ---------- RUNNING 	NEW 		BUILD ----------
./src/BlockWorld
