#ifndef COMMON_H
#define COMMON_H

enum Input{ NILL, W, S, A, D, SPACE, CTRL };
enum AssetType{ BW_CUBE, BW_STAR, BW_DIAMOND, BW_UNKNOWN };
enum BBoxType{ NONE, ROTATE, SCALE, TRANSLATE, FOLLOWPATH, SPECIAL}
#endif
